import asyncio
import sys
sys.path.append('.')

from services.firebase_service import delete_document, create_document, get_all_documents

# Karachi default coordinates: 24.8607, 67.0099
# Islamabad/Rawalpindi default coordinates: 33.6506, 72.9639

PROVIDERS_TO_SEED = [
    # --- KARACHI ---
    {
        "id": "ayesha-bibi-female-1",
        "name_en": "Ayesha Bibi",
        "name_ur": "Ayesha Bibi",
        "phone": "+923001234567",
        "service_type_id": "electrician",
        "pricing_type": "hourly",
        "hourly_rate": 900,
        "rate": 900,
        "area_name": "Saddar, Karachi",
        "lat": 24.8607,
        "lng": 67.0099,
        "gender": "female",
        "is_available": True,
        "rating": 4.8,
        "total_reviews": 3,
        "jobs_completed": 12,
        "cnic_verified": True,
        "experience_years": 3,
    },
    {
        "id": "tahira-parveen-female-2",
        "name_en": "Tahira Parveen",
        "name_ur": "Tahira Parveen",
        "phone": "+923007654321",
        "service_type_id": "electrician",
        "pricing_type": "hourly",
        "hourly_rate": 950,
        "rate": 950,
        "area_name": "Clifton, Karachi",
        "lat": 24.8138,
        "lng": 67.0016,
        "gender": "female",
        "is_available": True,
        "rating": 4.7,
        "total_reviews": 5,
        "jobs_completed": 8,
        "cnic_verified": True,
        "experience_years": 4,
    },
    {
        "id": "muhammad-ali-male-1",
        "name_en": "Muhammad Ali",
        "name_ur": "Muhammad Ali",
        "phone": "+923009998887",
        "service_type_id": "electrician",
        "pricing_type": "hourly",
        "hourly_rate": 800,
        "rate": 800,
        "area_name": "Gulshan-e-Iqbal, Karachi",
        "lat": 24.9180,
        "lng": 67.0971,
        "gender": "male",
        "is_available": True,
        "rating": 4.5,
        "total_reviews": 6,
        "jobs_completed": 15,
        "cnic_verified": True,
        "experience_years": 5,
    },
    {
        "id": "sajid-khan-male-2",
        "name_en": "Sajid Khan",
        "name_ur": "Sajid Khan",
        "phone": "+923001112223",
        "service_type_id": "electrician",
        "pricing_type": "hourly",
        "hourly_rate": 850,
        "rate": 850,
        "area_name": "DHA Phase 6, Karachi",
        "lat": 24.7950,
        "lng": 67.0500,
        "gender": "male",
        "is_available": True,
        "rating": 4.6,
        "total_reviews": 4,
        "jobs_completed": 10,
        "cnic_verified": True,
        "experience_years": 2,
    },
    # --- ISLAMABAD / RAWALPINDI ---
    {
        "id": "aleesha-female-3",
        "name_en": "Aleesha",
        "name_ur": "Aleesha",
        "phone": "+923004445556",
        "service_type_id": "electrician",
        "pricing_type": "hourly",
        "hourly_rate": 920,
        "rate": 920,
        "area_name": "G-11, Islamabad",
        "lat": 33.6534,
        "lng": 73.0069,
        "gender": "female",
        "is_available": True,
        "rating": 4.5,
        "total_reviews": 2,
        "jobs_completed": 4,
        "cnic_verified": True,
        "experience_years": 1,
    },
    {
        "id": "zainab-bibi-female-4",
        "name_en": "Zainab Bibi",
        "name_ur": "Zainab Bibi",
        "phone": "+923007778889",
        "service_type_id": "electrician",
        "pricing_type": "hourly",
        "hourly_rate": 880,
        "rate": 880,
        "area_name": "F-8, Islamabad",
        "lat": 33.7125,
        "lng": 73.0425,
        "gender": "female",
        "is_available": True,
        "rating": 4.9,
        "total_reviews": 7,
        "jobs_completed": 14,
        "cnic_verified": True,
        "experience_years": 6,
    },
    {
        "id": "baqir-raza-male-3",
        "name_en": "Baqir Raza",
        "name_ur": "Baqir Raza",
        "phone": "+923008889990",
        "service_type_id": "electrician",
        "pricing_type": "hourly",
        "hourly_rate": 750,
        "rate": 750,
        "area_name": "Saddar, Rawalpindi",
        "lat": 33.5950,
        "lng": 73.0550,
        "gender": "male",
        "is_available": True,
        "rating": 4.5,
        "total_reviews": 1,
        "jobs_completed": 3,
        "cnic_verified": True,
        "experience_years": 2,
    },
    {
        "id": "ali-reza-male-4",
        "name_en": "Ali Reza",
        "name_ur": "Ali Reza",
        "phone": "+923002223334",
        "service_type_id": "electrician",
        "pricing_type": "hourly",
        "hourly_rate": 900,
        "rate": 900,
        "area_name": "I-8, Islamabad",
        "lat": 33.6660,
        "lng": 73.0760,
        "gender": "male",
        "is_available": True,
        "rating": 4.7,
        "total_reviews": 9,
        "jobs_completed": 21,
        "cnic_verified": True,
        "experience_years": 7,
    },
    {
        "id": "babar-azam-male-5",
        "name_en": "Babar Azam",
        "name_ur": "Babar Azam",
        "phone": "+923005556667",
        "service_type_id": "electrician",
        "pricing_type": "hourly",
        "hourly_rate": 1000,
        "rate": 1000,
        "area_name": "Bahria Town, Islamabad",
        "lat": 33.5350,
        "lng": 73.1250,
        "gender": "male",
        "is_available": True,
        "rating": 5.0,
        "total_reviews": 2,
        "jobs_completed": 5,
        "cnic_verified": True,
        "experience_years": 5,
    },
    {
        "id": "yasir-shah-male-6",
        "name_en": "Yasir Shah",
        "name_ur": "Yasir Shah",
        "phone": "+923003334445",
        "service_type_id": "electrician",
        "pricing_type": "hourly",
        "hourly_rate": 800,
        "rate": 800,
        "area_name": "G-9, Islamabad",
        "lat": 33.6880,
        "lng": 73.0330,
        "gender": "male",
        "is_available": True,
        "rating": 4.4,
        "total_reviews": 11,
        "jobs_completed": 19,
        "cnic_verified": True,
        "experience_years": 6,
    }
]

async def main():
    print("Fetching existing providers...")
    existing = await get_all_documents("providers")
    print(f"Found {len(existing)} providers. Deleting all...")
    for p in existing:
        pid = p.get("id")
        if pid:
            await delete_document("providers", pid)
            print(f"Deleted {pid}")
            
    print("\nSeeding new providers...")
    for p in PROVIDERS_TO_SEED:
        await create_document("providers", p, p["id"])
        print(f"Seeded: {p['name_en']} ({p['gender']}) at {p['area_name']}")
        
    print("\nReseeding completed successfully!")

if __name__ == "__main__":
    asyncio.run(main())
