// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_tW2ktwcmydnounwXhzDU1dDT1_LV0AY',
    appId: '1:413186078039:web:bfa81840959400830dba12',
    messagingSenderId: '413186078039',
    projectId: 'khidmat-ai-e02fb',
    authDomain: 'khidmat-ai-e02fb.firebaseapp.com',
    storageBucket: 'khidmat-ai-e02fb.firebasestorage.app',
    measurementId: 'G-4LMWLLY5HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk70cWONSKeoQwoMZRfCYyrSoW8yC6Uyo',
    appId: '1:413186078039:android:186bfd377a0dddf60dba12',
    messagingSenderId: '413186078039',
    projectId: 'khidmat-ai-e02fb',
    storageBucket: 'khidmat-ai-e02fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwLSldzzZ43wZEeeKp-20dBYRJ5tMDl7o',
    appId: '1:413186078039:ios:501b0ed36be37fa10dba12',
    messagingSenderId: '413186078039',
    projectId: 'khidmat-ai-e02fb',
    storageBucket: 'khidmat-ai-e02fb.firebasestorage.app',
    iosBundleId: 'com.khidmat.khidmatAiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwLSldzzZ43wZEeeKp-20dBYRJ5tMDl7o',
    appId: '1:413186078039:ios:501b0ed36be37fa10dba12',
    messagingSenderId: '413186078039',
    projectId: 'khidmat-ai-e02fb',
    storageBucket: 'khidmat-ai-e02fb.firebasestorage.app',
    iosBundleId: 'com.khidmat.khidmatAiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_tW2ktwcmydnounwXhzDU1dDT1_LV0AY',
    appId: '1:413186078039:web:5a849ab823a1cc210dba12',
    messagingSenderId: '413186078039',
    projectId: 'khidmat-ai-e02fb',
    authDomain: 'khidmat-ai-e02fb.firebaseapp.com',
    storageBucket: 'khidmat-ai-e02fb.firebasestorage.app',
    measurementId: 'G-XSP3TKTMJN',
  );
}
